Evol init observatoire
departement-loire-atlantique/jPlatformSocle pull request #1001
Opened 2021-04-06 13:41 UTC by sguellec

Evol du tag "titleSimple"+ ajout de méthode utilitaire + ajout de labels qui serviront sur le site Observatoire.

2021-04-06 15:47 UTC, camille-david requested changes

2021-04-06 15:47 UTC, camille-david commented on WEB-INF/classes/fr/cg44/plugin/socle/SocleUtils.java
> +  public static boolean hasAncestorCat(Publication pub, Category ancestorCat) {
Je ne suis pas à l'aise avec la description de la méthode. Elle laisse entendre qu'elle regarde si une catégorie est un ancêtre d'une des catégories de la publication, qu'importe le degré de parenté.
Alors qu'en réalité elle vérifie si c'est un parent direct ou une des catégories de la publication.
Par exemple je m'attendrai à ce qu'elle retourne forcément true si je mettais la catégorie racine en entrée.

De plus c'est "anc**ê**tre" et pas "anc**è**tre", mais ça c'est moins important :P

2021-04-06 16:03 UTC, sguellec commented on WEB-INF/classes/fr/cg44/plugin/socle/SocleUtils.java
> +  public static boolean hasAncestorCat(Publication pub, Category ancestorCat) {
Non elle vérifie bien quelque soit le degré de parenté via la méthode native "hasAncestor".
Je l'ai nommé comme cela car elle ressemble justement à cette méthode native mais qui ne s'applique qu'à des catégories.
Après la description n'est sans doute pas très bien tournée.

2021-04-06 16:11 UTC, camille-david approved these changes

2021-04-07 07:12 UTC, camille-david approved these changes

2021-04-07 09:56 UTC, merged