Quickfix accessibilité : alt vide si figCaption
departement-loire-atlantique/jPlatformSocle pull request #1062
Opened 2021-05-31 09:20 UTC by LChoquet

2021-05-31 12:07 UTC, sguellec submitted a review, later dismissed

2021-05-31 12:17 UTC, sguellec reviewed
Si il y a un figcaption, il ne doit pas y avoir de alt. Même vide. Je crois que c'est ça qu'il faut mettre en place côté accessibilité. J'attends confirmation de Franck.

2021-05-31 15:19 UTC, sguellec requested changes
Après vérification auprès de Franck, il faut bien laisser le alt ET LE RENSEIGNER, s'il y a un figcaption. Prendre alors la valeur du figcaption pour la mettre aussi dans le alt

2021-06-01 07:52 UTC, mformont approved these changes

2021-06-01 09:29 UTC, sguellec approved these changes

2021-06-01 09:35 UTC, merged