1318 - fix superposition portlet push
departement-loire-atlantique/jPlatformSocle pull request #1075
Opened 2021-06-14 08:02 UTC by LChoquet

Lignes restaurées pour le bon DOM

2021-06-14 08:37 UTC, mformont approved these changes

2021-06-14 10:26 UTC, sguellec approved these changes

2021-06-15 07:34 UTC, mformont requested changes
Ne pas push /PortletPush/doPortletPushBoxDisplay.jsp  si pas de changements.

2021-06-15 08:08 UTC, mformont approved these changes

2021-06-15 08:14 UTC, merged