1861 : afficher la commune dans la tuile article/lieu
departement-loire-atlantique/jPlatformSocle pull request #1089
Opened 2021-06-28 14:49 UTC by mformont

2021-06-28 14:51 UTC, LChoquet requested changes
Un rien de petites fautes d'inattention à revoir :)

2021-06-28 14:51 UTC, LChoquet commented on plugins/SoclePlugin/jsp/cards/doFicheArticleCard.jsp
> +Boolean displayCommunesConcernees = "true".equals(request.getParameter("afficheCommunes"));;
Double points virgules !

2021-06-28 14:51 UTC, LChoquet commented on plugins/SoclePlugin/jsp/cards/doFicheLieuCard.jsp
> +Boolean displayCommunesConcernees = "true".equals(request.getParameter("afficheCommunes"));;
Double points virgules

2021-06-29 06:12 UTC, LChoquet approved these changes

2021-06-29 08:18 UTC, sguellec approved these changes

2021-06-29 08:20 UTC, merged