2035 - Champs SEO supplémentaires fiche aide
departement-loire-atlantique/jPlatformSocle pull request #1207
Opened 2021-12-15 09:06 UTC by LChoquet

2021-12-15 13:47 UTC, sguellec requested changes

2021-12-15 13:47 UTC, sguellec commented on plugins/SoclePlugin/types/FicheAide/doFicheAideFullDisplay.jsp
> +			                  <h2 id="idTitre2"><%= gtitrePourQui %></h2>
Faute de frappe ? Pas d'erreur à l'execution ?

2021-12-15 13:47 UTC, LChoquet commented on plugins/SoclePlugin/types/FicheAide/doFicheAideFullDisplay.jsp
> +			                  <h2 id="idTitre2"><%= gtitrePourQui %></h2>
Bah étrangement non, mais je vais changer ça.

2021-12-16 09:37 UTC, mformont approved these changes

2021-12-16 10:18 UTC, sguellec approved these changes

2021-12-16 10:19 UTC, merged