2115 - fix nb tuiles max carrousel
departement-loire-atlantique/jPlatformSocle pull request #1275
Opened 2022-05-09 08:03 UTC by LChoquet

2022-05-09 11:46 UTC, sguellec requested changes
Si tu inclus doForeachHeader.jspf et doForeachFooter.jspf, il ne faut pas intégrer de boucle dans le code. C'est la mécanique native qui va gérer l'itération et le nb max d'éléments etc.
Je pense qu'il faut juste mettre ces 2 "includes" autour du <li> et supprimer le foreach.
A tester...

2022-05-09 11:49 UTC, LChoquet commented
> Si tu inclus doForeachHeader.jspf et doForeachFooter.jspf, il ne faut pas intégrer de boucle dans le code. C'est la mécanique native qui va gérer l'itération et le nb max d'éléments etc. Je pense qu'il faut juste mettre ces 2 "includes" autour du
> 
> * et supprimer le foreach.
>   A tester...

Ces deux liens sont à supprimer, car bien qu'ils bouclent, certes, ils sont l'un à côté de l'autre et aucun code n'est situé entre deux. Donc aucune action n'est faite à chaque itération.
En somme, ça bouffe de la performance !

2022-05-10 06:51 UTC, sguellec approved these changes

2022-05-10 08:02 UTC, mformont requested changes

2022-05-10 08:28 UTC, mformont approved these changes

2022-05-10 08:50 UTC, sguellec approved these changes

2022-05-10 08:50 UTC, merged