Fix rs 1471 ajout reseaux sociaux ds footer archive
departement-loire-atlantique/jPlatformSocle pull request #688
Opened 2020-10-30 13:57 UTC by camille-david

https://refonte44.atlassian.net/browse/RS-1471

2020-10-30 14:40 UTC, LChoquet requested changes

2020-10-30 14:40 UTC, LChoquet commented on WEB-INF/plugins/SoclePlugin/properties/plugin.prop
> +# ------------------------------------------------------------
Si c'est pour les archives, autant mettre ça dans le plugin.prop du module archives ;)

2020-10-30 14:47 UTC, camille-david commented on WEB-INF/plugins/SoclePlugin/properties/plugin.prop
> +# ------------------------------------------------------------
Si c'est le cas je devrai mettre une dépendance du module socle vers le module archive ; à moins que je passe les fichiers du footer/header dans le module archive ?

2020-11-02 07:24 UTC, LChoquet approved these changes

2020-11-02 07:31 UTC, sguellec approved these changes

2020-11-02 07:54 UTC, merged