FIX_RS-1492_retours_test_fonctionnel
departement-loire-atlantique/jPlatformSocle pull request #721
Opened 2020-11-20 16:41 UTC by camille-david

+ minor fix ds attribut class ds figurePicture.tag

https://refonte44.atlassian.net/browse/RS-1492

2020-11-22 10:10 UTC, sguellec requested changes

2020-11-22 10:10 UTC, sguellec commented on WEB-INF/data/types/Lien/Lien.xml
>      </field>
La balise "description" n'est pas au bon endroit. Le "build" échoue du coup.

2020-11-22 10:12 UTC, sguellec requested changes

2020-11-22 10:12 UTC, sguellec commented on WEB-INF/data/types/Lien/Lien.xml
>      <field name="picto" editor="textfield" required="false" compactDisplay="false" type="String" searchable="false" size="80" ml="false" html="false" checkHtml="true" descriptionType="tooltip" tab="c
La balise "description" n'est pas au bon endroit. Le "build" échoue du coup.

2020-11-23 08:09 UTC, LChoquet approved these changes

2020-11-23 16:14 UTC, sguellec approved these changes

2020-11-24 07:23 UTC, merged