FIX RS-1514 attribut title lien mieux nous connaitre grands projets
departement-loire-atlantique/jPlatformSocle pull request #732
Opened 2020-11-24 09:51 UTC by camille-david

https://refonte44.atlassian.net/browse/RS-1514

2020-11-24 09:52 UTC, LChoquet approved these changes

2020-11-24 16:47 UTC, sguellec requested changes

2020-11-24 16:47 UTC, sguellec commented on plugins/SoclePlugin/types/PortletMiseEnAvantDeContenus/doPortletMiseEnAvantDeContenusBoxGrandsProjets.jsp
> +String titleAttr = Util.notEmpty(box.getTitreCompletDeLien()) ? box.getTitreCompletDeLien() : labelBouton;
Detail mais je préférerais que tu gardes "titleValue" comme variable. "titleAttr" était à la base prévu pour générer tout l'attribut (attribut et sa valeur). 
Dans certains cas, niveau accessibilité il était demandé de ne pas générer d'attribut "title", d'où la présence des 2 variables.

2020-11-25 10:56 UTC, sguellec approved these changes

2020-11-25 12:52 UTC, merged