Hotfix tuile horizontale
departement-loire-atlantique/jPlatformSocle pull request #754
Opened 2020-11-27 10:09 UTC by sguellec

Génère une exception pour les types qui ne sont pas des "Lien".

2020-11-27 10:12 UTC, LChoquet commented on plugins/SoclePlugin/jsp/templates/tuileHorizontale.jsp
> +                        if(pub instanceof Lien && Util.notEmpty(pub.getFieldValue("lienExterne"))) altText = glp("jcmsplugin.socle.lien.nouvelonglet", altText);
Ca ne serait pas mieux d'entourer d'un try / catch pour englober tous les (futurs) contenus et pas des cas spécifiques ?

2020-11-30 12:22 UTC, sguellec commented on plugins/SoclePlugin/jsp/templates/tuileHorizontale.jsp
> +                        if(pub instanceof Lien && Util.notEmpty(pub.getFieldValue("lienExterne"))) altText = glp("jcmsplugin.socle.lien.nouvelonglet", altText);
Absolument !

2020-11-30 12:30 UTC, LChoquet approved these changes

2020-11-30 12:31 UTC, LChoquet requested changes

2020-11-30 12:31 UTC, LChoquet commented on plugins/SoclePlugin/jsp/templates/tuileHorizontale.jsp
> +                          altText = glp("jcmsplugin.socle.lien.nouvelonglet", pub.getFieldValue("lienExterne"));
Il y  a une méthode SocleUtils.getAltTextFromPublication

2020-11-30 13:09 UTC, camille-david approved these changes

2020-11-30 13:31 UTC, sguellec commented on plugins/SoclePlugin/jsp/templates/tuileHorizontale.jsp
> +                          altText = glp("jcmsplugin.socle.lien.nouvelonglet", pub.getFieldValue("lienExterne"));
OK. Mais ce code est assez ancien. Un refacto général est peut-être nécessaire.

2020-11-30 17:07 UTC, closed without merging

2020-11-30 17:08 UTC, sguellec commented
Les modifs seront traitées dans cet autre PR : 
https://github.com/departement-loire-atlantique/jPlatformSocle/pull/760