150 - champ "alt" cas particulier fiche lieu
departement-loire-atlantique/jPlatformSocle pull request #755
Opened 2020-11-27 14:27 UTC by LChoquet

2020-11-27 14:28 UTC, sguellec approved these changes

2020-11-27 16:10 UTC, camille-david requested changes

2020-11-27 16:10 UTC, camille-david commented on plugins/SoclePlugin/types/FicheLieu/doFicheLieuFullDisplay.jsp
> +                                String altTxt = SocleUtils.getAltTextFromPub(obj);
La variable est utilisée quelque part ?

2020-11-27 16:10 UTC, camille-david commented on plugins/SoclePlugin/types/FicheLieu/doFicheLieuFullDisplay.jsp
> +                                <img src='<%= SocleUtils.getUrlOfFormattedImagePrincipale(obj.getImagePrincipale()) %>' class="ds44-w100 ds44-imgRatio" alt="<%= SocleUtils.getAltTextFromPub(obj) %>">
il manquerait juste `HttpUtil.encodeForHTMLAttribute()` pour le alt

2020-11-30 08:13 UTC, camille-david approved these changes

2020-11-30 17:06 UTC, sguellec approved these changes

2020-12-01 07:24 UTC, merged