FIX RS-1526 alt tuile horizontale + REFACTO getAltTextFromPub
departement-loire-atlantique/jPlatformSocle pull request #760
Opened 2020-11-30 14:24 UTC by camille-david

https://refonte44.atlassian.net/browse/RS-1526

2020-11-30 14:26 UTC, LChoquet approved these changes

2020-11-30 16:57 UTC, sguellec requested changes
cf commentaire sur la tuile horizontale.

2020-11-30 16:57 UTC, sguellec commented on plugins/SoclePlugin/jsp/templates/tuileHorizontale.jsp
>                          titleAttr = " title=\"" + HttpUtil.encodeForHTMLAttribute(altText) + "\"";
En fait j'ai un PR en cours avec des modif sur la tuile horizontale. Je pense qu'on va l'annuler puisque cette version est bien + complète.
Juste intégrer le try/catch autour du "pub.getFieldValue("lienExterne")" car ça génère une exception si le champ n'est pas présent dans le type de contenu.

2020-12-01 14:57 UTC, sguellec approved these changes

2020-12-01 15:06 UTC, merged