RS-719 Ré écriture d'url pour recherche à facettes
departement-loire-atlantique/jPlatformSocle pull request #841
Opened 2020-12-18 15:09 UTC by mformont

2020-12-18 15:20 UTC, LChoquet approved these changes

2020-12-21 06:55 UTC, LChoquet requested changes
Travis indique une erreur au démarrage de SoclePlugin. Peut-être revoir le plugin.xml ?

2021-01-04 10:36 UTC, camille-david approved these changes

2021-01-11 14:39 UTC, LChoquet approved these changes

2021-01-12 14:54 UTC, sguellec approved these changes

2021-01-12 15:24 UTC, merged