Evol : form contact (RS-1651)
departement-loire-atlantique/jPlatformSocle pull request #865
Opened 2021-01-15 16:13 UTC by sguellec

Gestion du formulaire front en multilingue

2021-01-15 16:38 UTC, camille-david requested changes

2021-01-15 16:38 UTC, camille-david commented on WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
> +
Il y a déjà d'autres propriétés socle qui ont "Nom", "Prénom", etc...
Est-ce que ça ne vaudrait pas le coup d'utiliser les propriétés déjà existantes ?

2021-01-15 17:49 UTC, sguellec commented on WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
> +
Oui j'avais vu en effet mais grosse flemme de refacto ! Je voulais continuer sur la syntaxe "jcmsplugin.socle.form.XXX", mais les autres champs sont de type "jcmsplugin.socle.XXX".
Je vais regarder ça de + près et voir quelle syntaxe est mieux.

2021-01-18 09:13 UTC, LChoquet commented on plugins/SoclePlugin/jsp/cards/doFicheEmploiStageCard.jsp
> +			    <i class="icon icon-marker ds44-docListIco" aria-hidden="true"></i><span class="visually-hidden"><%= glp("jcmsplugin.socle.adresse") %> : </span>
Tous les : ne peuvent pas être ajoutés dans les fichiers prop de langues ?

2021-01-18 09:22 UTC, LChoquet approved these changes

2021-01-18 09:39 UTC, camille-david approved these changes

2021-01-18 09:48 UTC, sguellec commented on plugins/SoclePlugin/jsp/cards/doFicheEmploiStageCard.jsp
> +			    <i class="icon icon-marker ds44-docListIco" aria-hidden="true"></i><span class="visually-hidden"><%= glp("jcmsplugin.socle.adresse") %> : </span>
Dans ces cas précis, le label est aussi utilisé ailleurs mais sans les " : ", donc pour ne pas doublonner les props avec un même label, on est parti sur l'idée que les  " : " seront mis dans les gabarits.

2021-01-18 09:49 UTC, merged