Fix :  Remplace le titre de l'url par le titre de la recherche à facette
departement-loire-atlantique/jPlatformSocle pull request #872
Opened 2021-01-25 14:28 UTC by mformont

2021-01-25 14:30 UTC, LChoquet approved these changes

2021-01-25 15:27 UTC, camille-david approved these changes

2021-01-26 12:50 UTC, sguellec requested changes

2021-01-26 12:50 UTC, sguellec commented on plugins/SoclePlugin/types/PortletRechercheFacettes/doPortletRechercheFacettesBoxDisplay.jsp
> +		String descFacet = DescriptiveURLs.cleanDescriptiveURLText(obj.getTitre(userLang), userLocale);
Tu as 2 points virgules. Ca n'a pas l'air gênant mais bon...

2021-01-26 15:48 UTC, mformont commented on plugins/SoclePlugin/types/PortletRechercheFacettes/doPortletRechercheFacettesBoxDisplay.jsp
> +		String descFacet = DescriptiveURLs.cleanDescriptiveURLText(obj.getTitre(userLang), userLocale);
Corrigé

2021-01-27 09:18 UTC, merged