FIX RS-1647 full display exposition style h2 et emplacement infos libres
departement-loire-atlantique/jPlatformSocle pull request #928
Opened 2021-02-23 15:46 UTC by camille-david

https://refonte44.atlassian.net/browse/RS-1647

2021-02-23 15:52 UTC, mformont approved these changes

2021-02-23 16:58 UTC, sguellec commented on plugins/SoclePlugin/types/Exposition/doExpositionFullDisplay.jsp
> +									<jalios:foreach name="itParagraphe" type="String" counter="itCounter" array="<%=obj.getContenuInfosLibres(userLang)%>">
Peut-être remettre le <jalios:if> si le champ est vide non ?

2021-02-23 17:00 UTC, sguellec requested changes
Cf commentaire sur fulldisplay

2021-03-01 08:22 UTC, camille-david commented on plugins/SoclePlugin/types/Exposition/doExpositionFullDisplay.jsp
> +									<jalios:foreach name="itParagraphe" type="String" counter="itCounter" array="<%=obj.getContenuInfosLibres(userLang)%>">
Petite note, si le champ est vide ça ne rentre simplement pas dans la boucle. Par contre j'avais bien oublié de rajouter le champ dans le test d'affichage des infos pratiques.

2021-03-01 08:47 UTC, mformont commented on plugins/SoclePlugin/types/Exposition/doExpositionFullDisplay.jsp
> +									<jalios:foreach name="itParagraphe" type="String" counter="itCounter" array="<%=obj.getContenuInfosLibres(userLang)%>">
Ok mais attention après un redémarrage serveur le champ peut devenir "null" et donc faire crasher ta boucle (Jalios remplace tous les tableaux vides par un null après un redémarrage tant que tu n'as pas édité le contenu). Je te laisse tester ce cas histoire d'être sûr. 
-> Vider le champ du tableau, redémarrer, afficher le gabarit.

2021-03-01 08:59 UTC, LChoquet approved these changes
OK pour moi une fois le point remonté par Mickael traité

2021-03-01 09:33 UTC, merged