1735 - Export fiche lieu sans accessibilité
departement-loire-atlantique/jPlatformSocle pull request #944
Opened 2021-03-02 15:39 UTC by LChoquet

2021-03-02 15:57 UTC, mformont approved these changes

2021-03-03 08:23 UTC, sguellec requested changes
Juste un détail à rectifier

2021-03-03 08:23 UTC, sguellec commented on plugins/SoclePlugin/jsp/export/exportInterface.jsp
> +    <input class="btn btn-info modal confirm" type="submit" value="G�n�rer le ZIP pour les images : Fiche Lieu"/>
Mauvaise value d'input pour le submit !

2021-03-03 08:26 UTC, LChoquet commented on plugins/SoclePlugin/jsp/export/exportInterface.jsp
> +    <input class="btn btn-info modal confirm" type="submit" value="G�n�rer le ZIP pour les images : Fiche Lieu"/>
Je ne comprends pas ? Le type de contenu est "FicheLieu" à la manière de "FicheArticle" plus haut...

2021-03-03 09:00 UTC, sguellec commented on plugins/SoclePlugin/jsp/export/exportInterface.jsp
> +    <input class="btn btn-info modal confirm" type="submit" value="G�n�rer le ZIP pour les images : Fiche Lieu"/>
erreur de ma part

2021-03-03 09:57 UTC, sguellec approved these changes

2021-03-03 10:21 UTC, merged