1794 - évolutions fiche action édu
departement-loire-atlantique/jPlatformSocle pull request #973
Opened 2021-03-25 09:42 UTC by LChoquet

2021-03-25 14:28 UTC, sguellec requested changes

2021-03-25 14:28 UTC, sguellec commented on WEB-INF/data/types/FicheActionEducative/FicheActionEducative.xml
> +      <label xml:lang="fr">Tafif</label>
Oh

2021-03-25 14:29 UTC, LChoquet commented on WEB-INF/data/types/FicheActionEducative/FicheActionEducative.xml
> +      <label xml:lang="fr">Tafif</label>
Le renommage a été demandé sur le ticket

2021-03-26 08:27 UTC, camille-david approved these changes

2021-03-26 08:35 UTC, sguellec approved these changes

2021-03-26 08:46 UTC, merged